export const ORIGINAL_DATA = [
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 1",
    startDate: "2023-02-20T00:00:00",
    finishDate: "2023-02-20T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 71,
    roomId: 71,
    roomType: "Physical",
    roomCode: "AAA",
    roomName: "AAA",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 57,
    subjectCode: "BSBADM301B",
    subjectName: "Produce Texts From Shorthand Notes",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 102,
    teacherName: "John  Doe",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 1",
    startDate: "2023-02-21T00:00:00",
    finishDate: "2023-02-21T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 71,
    roomId: 71,
    roomType: "Physical",
    roomCode: "AAA",
    roomName: "AAA",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 57,
    subjectCode: "BSBADM301B",
    subjectName: "Produce Texts From Shorthand Notes",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 102,
    teacherName: "John  Doe",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 1",
    startDate: "2023-02-22T00:00:00",
    finishDate: "2023-02-22T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 71,
    roomId: 71,
    roomType: "Physical",
    roomCode: "AAA",
    roomName: "AAA",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 57,
    subjectCode: "BSBADM301B",
    subjectName: "Produce Texts From Shorthand Notes",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 102,
    teacherName: "John  Doe",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 1",
    startDate: "2023-02-23T00:00:00",
    finishDate: "2023-02-23T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 71,
    roomId: 71,
    roomType: "Physical",
    roomCode: "AAA",
    roomName: "AAA",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 57,
    subjectCode: "BSBADM301B",
    subjectName: "Produce Texts From Shorthand Notes",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 102,
    teacherName: "John  Doe",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 1",
    startDate: "2023-02-24T00:00:00",
    finishDate: "2023-02-24T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 71,
    roomId: 71,
    roomType: "Physical",
    roomCode: "AAA",
    roomName: "AAA",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 57,
    subjectCode: "BSBADM301B",
    subjectName: "Produce Texts From Shorthand Notes",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 102,
    teacherName: "John  Doe",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 1",
    startDate: "2023-02-20T00:00:00",
    finishDate: "2023-02-20T00:00:00",
    startTime: "07:00:00",
    finishTime: "10:00:00",
    hasBreak: true,
    resourceId: 76,
    roomId: 76,
    roomType: "Physical",
    roomCode: "RC004",
    roomName: "Room 1",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 194,
    subjectCode: "adad",
    subjectName: "Math basic",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 62,
    teacherName: "Nathan   Lyan",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 1",
    startDate: "2023-02-22T00:00:00",
    finishDate: "2023-02-22T00:00:00",
    startTime: "07:00:00",
    finishTime: "10:00:00",
    hasBreak: true,
    resourceId: 76,
    roomId: 76,
    roomType: "Physical",
    roomCode: "RC004",
    roomName: "Room 1",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 194,
    subjectCode: "adad",
    subjectName: "Math basic",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 62,
    teacherName: "Nathan   Lyan",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 1",
    startDate: "2023-02-24T00:00:00",
    finishDate: "2023-02-24T00:00:00",
    startTime: "07:00:00",
    finishTime: "10:00:00",
    hasBreak: true,
    resourceId: 76,
    roomId: 76,
    roomType: "Physical",
    roomCode: "RC004",
    roomName: "Room 1",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 194,
    subjectCode: "adad",
    subjectName: "Math basic",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 62,
    teacherName: "Nathan   Lyan",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 2",
    startDate: "2023-02-20T00:00:00",
    finishDate: "2023-02-20T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 91,
    roomId: 91,
    roomType: "Physical",
    roomCode: "ttt",
    roomName: "Paramatta Room",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 22,
    subjectCode: "BSBITU1123",
    subjectName: "Develop keyboard skills",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 2",
    startDate: "2023-02-21T00:00:00",
    finishDate: "2023-02-21T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 91,
    roomId: 91,
    roomType: "Physical",
    roomCode: "ttt",
    roomName: "Paramatta Room",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 22,
    subjectCode: "BSBITU1123",
    subjectName: "Develop keyboard skills",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 2",
    startDate: "2023-02-22T00:00:00",
    finishDate: "2023-02-22T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 91,
    roomId: 91,
    roomType: "Physical",
    roomCode: "ttt",
    roomName: "Paramatta Room",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 22,
    subjectCode: "BSBITU1123",
    subjectName: "Develop keyboard skills",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 2",
    startDate: "2023-02-20T00:00:00",
    finishDate: "2023-02-20T00:00:00",
    startTime: "07:00:00",
    finishTime: "10:00:00",
    hasBreak: true,
    resourceId: 91,
    roomId: 91,
    roomType: "Physical",
    roomCode: "ttt",
    roomName: "Paramatta Room",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 119,
    subjectCode: "BSBXCM501",
    subjectName: "Discrete Mathematics",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 14,
    teacherName: "ASHIS  THAPA",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 2",
    startDate: "2023-02-21T00:00:00",
    finishDate: "2023-02-21T00:00:00",
    startTime: "07:00:00",
    finishTime: "10:00:00",
    hasBreak: true,
    resourceId: 91,
    roomId: 91,
    roomType: "Physical",
    roomCode: "ttt",
    roomName: "Paramatta Room",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 119,
    subjectCode: "BSBXCM501",
    subjectName: "Discrete Mathematics",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 14,
    teacherName: "ASHIS  THAPA",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 2",
    startDate: "2023-02-24T00:00:00",
    finishDate: "2023-02-24T00:00:00",
    startTime: "07:00:00",
    finishTime: "10:00:00",
    hasBreak: true,
    resourceId: 91,
    roomId: 91,
    roomType: "Physical",
    roomCode: "ttt",
    roomName: "Paramatta Room",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 194,
    subjectCode: "adad",
    subjectName: "Math basic",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 2",
    startDate: "2023-02-22T00:00:00",
    finishDate: "2023-02-22T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 91,
    roomId: 91,
    roomType: "Physical",
    roomCode: "ttt",
    roomName: "Paramatta Room",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 72,
    subjectCode: "31245",
    subjectName: "Business Process and IT Strategy",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 84,
    teacherName: "taylor",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET 2023 Cohort 2",
    startDate: "2023-02-23T00:00:00",
    finishDate: "2023-02-23T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 91,
    roomId: 91,
    roomType: "Physical",
    roomCode: "ttt",
    roomName: "Paramatta Room",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 97,
    subjectCode: "TAEDEL400",
    subjectName: "Workplace management",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET2023T1_AM",
    startDate: "2023-02-23T00:00:00",
    finishDate: "2023-02-23T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 76,
    roomId: 76,
    roomType: "Physical",
    roomCode: "RC004",
    roomName: "Room 1",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 98,
    subjectCode: "TAEDEL403",
    subjectName: "Coordinate and facilitate distance-based learning",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET2023T1_AM",
    startDate: "2023-02-24T00:00:00",
    finishDate: "2023-02-24T00:00:00",
    startTime: "07:00:00",
    finishTime: "11:00:00",
    hasBreak: false,
    resourceId: 76,
    roomId: 76,
    roomType: "Physical",
    roomCode: "RC004",
    roomName: "Room 1",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 98,
    subjectCode: "TAEDEL403",
    subjectName: "Coordinate and facilitate distance-based learning",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET2023T1_AM",
    startDate: "2023-02-20T00:00:00",
    finishDate: "2023-02-20T00:00:00",
    startTime: "07:00:00",
    finishTime: "10:00:00",
    hasBreak: true,
    resourceId: 71,
    roomId: 71,
    roomType: "Physical",
    roomCode: "AAA",
    roomName: "AAA",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 99,
    subjectCode: "TAEDEL404",
    subjectName: "Mentor in the workplace",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "VET2023T1_AM",
    startDate: "2023-02-21T00:00:00",
    finishDate: "2023-02-21T00:00:00",
    startTime: "07:00:00",
    finishTime: "10:00:00",
    hasBreak: true,
    resourceId: 71,
    roomId: 71,
    roomType: "Physical",
    roomCode: "AAA",
    roomName: "AAA",
    venueId: 7,
    venueCode: "S302",
    venueDescription: "Sydney CBD Venue",
    subjectId: 99,
    subjectCode: "TAEDEL404",
    subjectName: "Mentor in the workplace",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "Sem1 Cohort A",
    startDate: "2023-02-20T00:00:00",
    finishDate: "2023-02-20T00:00:00",
    startTime: "09:00:00",
    finishTime: "12:00:00",
    hasBreak: false,
    resourceId: 107,
    roomId: 107,
    roomType: "Physical",
    roomCode: "RC1111",
    roomName: "Room ",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 56,
    subjectCode: "CN001",
    subjectName: "Computer Networking",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "Sem1 Cohort A",
    startDate: "2023-02-22T00:00:00",
    finishDate: "2023-02-22T00:00:00",
    startTime: "09:00:00",
    finishTime: "12:00:00",
    hasBreak: false,
    resourceId: 107,
    roomId: 107,
    roomType: "Physical",
    roomCode: "RC1111",
    roomName: "Room ",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 56,
    subjectCode: "CN001",
    subjectName: "Computer Networking",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
  {
    campusId: 2,
    campusCode: "SYD",
    campusName: "Sydney Campus",
    cohortName: "Sem1 Cohort A",
    startDate: "2023-02-24T00:00:00",
    finishDate: "2023-02-24T00:00:00",
    startTime: "09:00:00",
    finishTime: "11:00:00",
    hasBreak: true,
    resourceId: 107,
    roomId: 107,
    roomType: "Physical",
    roomCode: "RC1111",
    roomName: "Room ",
    venueId: 11,
    venueCode: "PRT304",
    venueDescription: "Parramatta Venue",
    subjectId: 56,
    subjectCode: "CN001",
    subjectName: "Computer Networking",
    moduleId: 0,
    moduleCode: "",
    moduleName: "",
    teachereId: 18,
    teacherName: "zyohtiee",
  },
];
